### ISSUE TITLE
Incorrect timeouts in J2SSHConnection

### ISSUE THREAD

**Issue by windgan** [Fob/Commons-SSH#12]
There is the following piece of code in connectImpl() method:

    Long timeout = ConnectionPropertiesBuilder.getInstance().getConnectTimeout(this);
    if (timeout != null)
        connection.setSocketTimeout(timeout.intValue());
    ...
    timeout = ConnectionPropertiesBuilder.getInstance().getSoTimeout(this);
    if (timeout != null)
        connection.setSocketTimeout(timeout.intValue());

I think it is incorrect, because we set socket timeout twice with different values.

**Comment by WinZib** [comment]
resolved in 2.2.0
